apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: prometheus
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: grafana.local.cluster
      http:
        paths:
          - backend:
              serviceName: prometheus-grafana
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: prometheus
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: prometheus.local.cluster
      http:
        paths:
          - backend:
              serviceName: prometheus-kube-prometheus-prometheus
              servicePort: 9090